In [27]:
!pip install pandas
!pip install simple_salesforce
from matchingFunctions import *

Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (0.24.2)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas) (2019.1)
Requirement already satisfied: numpy>=1.12.0 in /anaconda3/lib/python3.7/site-packages (from pandas) (1.16.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /anaconda3/lib/python3.7/site-packages (from pandas) (2.8.0)
Requirement already satisfied: six>=1.5 in /anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)
Requirement already satisfied: simple_salesforce in /anaconda3/lib/python3.7/site-packages (1.11.1)
Requirement already satisfied: requests>=2.22.0 in /anaconda3/lib/python3.7/site-packages (from simple_salesforce) (2.22.0)
Requirement already satisfied: authlib in /anaconda3/lib/python3.7/site-packages (from simple_salesforce) (0.15.3)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests>=2.22.0->simple_salesforce) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests>=2.22.0->simple_salesforce) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests>=2.22.0->simple_salesforce) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests>=2.22.0->simple_salesforce) (1.25.10)
Requirement already satisfied: cryptography in /anaconda3/lib/python3.7/site-packages (from authlib->simple_salesforce) (2.7)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /anaconda3/lib/python3.7/site-packages (from cryptography->authlib->simple_salesforce) (1.12.3)
Requirement already satisfied: six>=1.4.1 in /anaconda3/lib/python3.7/site-packages (from cryptography->authlib->simple_salesforce) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /anaconda3/lib/python3.7/site-packages (from cryptography->authlib->simple_salesforce) (0.24.0)
Requirement already satisfied: pycparser in /anaconda3/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->authlib->simple_salesforce) (2.19)

In [28]:
sf = createSalesforceConnection()

In [29]:
cases = createCaseDF(sf)

In [30]:
suppliers = createSupplierDF(sf)

In [31]:
objectxs = createObjectxDF(sf)

In [32]:
objectxsFiltered = mergeAndFilterObjXs(objectxs, suppliers, cases)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [33]:
laboredge = createLaboredgeDF()

In [34]:
##files = createFileDF()
files = pd.DataFrame()

In [35]:
laboredgeMerged = createLaboredgeMergedDF(laboredge, objectxsFiltered, files)

In [36]:
laboredgeMatched = createLaboredgeMatchedDF(laboredgeMerged)

In [39]:
objectxs.to_csv('prevObjectXs.csv')
objectxsFiltered.to_csv('prevObjectXsFiltered.csv')
laboredge.to_csv('prevLaboredge.csv')
laboredgeMerged.to_csv('prevLaboredgeMerged.csv')
laboredgeMatched.to_csv('laboredgeMatched.csv')

In [37]:
laboredgeMerged[laboredgeMerged['Object X ID'].isnull() != False]

Empty DataFrame
Columns: [Deal Date, Case #, Client, Service Provider, OEM Company, Product/Category, Level, Position Title, Hours, exp Low, exp High, Country, City/State, qtd Low, qtd High, tgt Low, tgt High, Deal Total, Currency Notes, Document Name, Service Provider U, Object X ID]
Index: []

[0 rows x 22 columns]

In [38]:
laboredgeMatched.sort_values('Input Date')

,Input Date,Object X ID,OEM Company,Product/Category,Level,Position Title,Hours,Years Exp High,Years Exp Low,Quoted Rate High,Quoted Rate Low,CEP Provided Rate High,CEP Provided Rate Low,Deal Total,Country,City/State,Currency Notes,Document Name,Database Practice
13514,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Managing Director,NaN,NaN,NaN,NaN,333.000000,350.0,325.0,NaN,USA,NaN,NaN,NaN,Services
7130,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Senior Consultant,NaN,NaN,NaN,NaN,159.000000,190.0,150.0,NaN,USA,NaN,NaN,NaN,Services
17494,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Director,NaN,NaN,NaN,NaN,282.000000,330.0,275.0,NaN,USA,NaN,NaN,NaN,Services
23875,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Associate Director,NaN,NaN,NaN,NaN,231.000000,280.0,230.0,NaN,USA,NaN,NaN,NaN,Services
13599,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Manager,NaN,NaN,NaN,NaN,195.000000,225.0,185.0,NaN,USA,NaN,NaN,NaN,Services
6656,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Senior Manager,NaN,NaN,NaN,NaN,220.000000,250.0,210.0,NaN,USA,NaN,NaN,NaN,Services
21724,2018-01-04,a1t2J000005Ypl6QAC,NaN,Internal Audit,NaN,Consultant,NaN,NaN,NaN,NaN,133.000000,155.0,125.0,NaN,USA,NaN,NaN,NaN,Services
18706,2018-01-05,a1t2J000005OXyLQAW,NaN,NaN,NaN,Delivery Manager,NaN,NaN,NaN,NaN,225.000000,275.0,190.0,NaN,USA,NaN,NaN,NaN,Services
4151,2018-01-05,a1t2J000005OXyLQAW,NaN,NaN,NaN,Senior Technical Consultant,NaN,NaN,NaN,NaN,225.000000,250.0,185.0,NaN,USA,NaN,NaN,NaN,Services
3989,2018-01-09,a1t2J000005YpwYQAS,NaN,Storage planning and implementation,NaN,Storage Consultants,NaN,NaN,NaN,NaN,270.000000,285.0,245.0,NaN,USA,NaN,NaN,NaN,Services
16776,2018-01-09,a1t2J000005YpwYQAS,NaN,Storage installation,NaN,Field Support Engineer,NaN,NaN,NaN,NaN,197.340000,240.0,175.0,NaN,USA,NaN,NaN,NaN,Services
12354,2018-01-09,a1t2J000005YpwYQAS,NaN,Workload measurements,NaN,OCI Consultant,NaN,NaN,NaN,NaN,270.000000,285.0,245.0,NaN,USA,NaN,NaN,NaN,Services
13095,2018-01-09,a1t2J000005YpwYQAS,NaN,NAS migration,NaN,Migration Consultants,NaN,NaN,NaN,NaN,105.300000,110.0,50.0,NaN,India,NaN,NaN,NaN,Services
6603,2018-01-09,a1t2J000005YpwYQAS,NaN,NAS migration lead,NaN,Senior Migration Consultant,NaN,NaN,NaN,NaN,270.000000,285.0,245.0,NaN,USA,NaN,NaN,NaN,Services
3069,2018-01-09,a1t2J000005YpwYQAS,NaN,Documentation,NaN,Tech Writer,NaN,NaN,NaN,NaN,243.750000,255.0,225.0,NaN,USA,NaN,NaN,NaN,Services
16828,2018-01-09,a1t2J000005YplLQAS,NaN,NaN,NaN,Expert Remote Services,NaN,NaN,NaN,NaN,225.230000,280.0,200.0,NaN,USA,NaN,NaN,NaN,Services
9750,2018-01-09,a1t2J000005YpwYQAS,NaN,Project management,NaN,Project Manager,NaN,NaN,NaN,NaN,243.750000,275.0,235.0,NaN,USA,NaN,NaN,NaN,Services
24729,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Application Architect,NaN,NaN,NaN,NaN,42.994220,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
7272,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Senior Configuration Developer,NaN,NaN,NaN,NaN,93.641618,NaN,NaN,NaN,USA,NaN,NaN,NaN,Services
10665,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Program Manager,NaN,NaN,NaN,NaN,147.976879,NaN,NaN,NaN,USA,NaN,NaN,NaN,Services
13998,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Lead Solution Architect,NaN,NaN,NaN,NaN,147.976879,NaN,NaN,NaN,USA,NaN,NaN,NaN,Services
2570,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Technical Lead (application),NaN,NaN,NaN,NaN,35.034682,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
16384,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Functional Solution SME,NaN,NaN,NaN,NaN,41.358382,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
4601,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Sr. BA / Functional SME,NaN,NaN,NaN,NaN,93.254335,NaN,NaN,NaN,USA,NaN,NaN,NaN,Services
4602,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Sr. BA,NaN,NaN,NaN,NaN,37.219653,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
6906,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Senior Developer,NaN,NaN,NaN,NaN,26.271676,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
11468,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,PM,NaN,NaN,NaN,NaN,46.710983,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
6972,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Senior Data Tester,NaN,NaN,NaN,NaN,85.225434,NaN,NaN,NaN,USA,NaN,NaN,NaN,Services
14480,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Junior QA Tester,NaN,NaN,NaN,NaN,18.248555,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
14539,2018-01-16,a1t2J000005YqJ8QAK,NaN,NaN,NaN,Junior Developer,NaN,NaN,NaN,NaN,21.895954,NaN,NaN,NaN,India,NaN,NaN,NaN,Services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4937,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,SQA Lead,NaN,NaN,NaN,NaN,40.500000,40.0,30.0,NaN,Offshore / India,NaN,NaN,NaN,Services
10616,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Program Manager,NaN,NaN,NaN,NaN,200.000000,220.0,115.0,NaN,USA,NaN,NaN,NaN,Services
4939,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,SQA,NaN,NaN,NaN,NaN,31.500000,35.0,25.0,NaN,Offshore / India,NaN,NaN,NaN,Services
23705,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,BA,NaN,NaN,NaN,NaN,175.000000,215.0,125.0,NaN,USA,NaN,NaN,NaN,Services
24020,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Architect/Lead,NaN,NaN,NaN,NaN,200.000000,280.0,175.0,NaN,USA,NaN,NaN,NaN,Services
10064,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Project Manager,NaN,NaN,NaN,NaN,49.500000,55.0,35.0,NaN,Offshore / India,NaN,NaN,NaN,Services
11716,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Performance & Security Testing Expert,NaN,NaN,NaN,NaN,31.500000,50.0,35.0,NaN,Offshore / India,NaN,NaN,NaN,Services
10351,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Project Director,NaN,NaN,NaN,NaN,170.000000,300.0,210.0,NaN,USA,NaN,NaN,NaN,Services
4938,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,SQA,NaN,NaN,NaN,NaN,80.000000,120.0,80.0,NaN,USA,NaN,NaN,NaN,Services
24102,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Architect,NaN,NaN,NaN,NaN,49.500000,60.0,40.0,NaN,Offshore / India,NaN,NaN,NaN,Services
14252,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Lead Business Analyst,NaN,NaN,NaN,NaN,140.000000,250.0,165.0,NaN,USA,NaN,NaN,NaN,Services
6898,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Senior Developer,NaN,NaN,NaN,NaN,225.000000,225.0,150.0,NaN,USA,NaN,NaN,NaN,Services
2474,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Technical Project Manager,NaN,NaN,NaN,NaN,49.500000,55.0,35.0,NaN,Offshore / India,NaN,NaN,NaN,Services
24098,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Architect,NaN,NaN,NaN,NaN,140.000000,225.0,115.0,NaN,USA,NaN,NaN,NaN,Services
18827,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,DBA/UI Team,NaN,NaN,NaN,NaN,80.000000,120.0,80.0,NaN,USA,NaN,NaN,NaN,Services
18394,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Dev . Config Interface,NaN,NaN,NaN,NaN,34.200000,50.0,25.0,NaN,Offshore / India,NaN,NaN,NaN,Services
2473,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Technical Project Manager,NaN,NaN,NaN,NaN,140.000000,220.0,140.0,NaN,USA,NaN,NaN,NaN,Services
23150,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Business Analyst,NaN,NaN,NaN,NaN,39.600000,45.0,30.0,NaN,Offshore / India,NaN,NaN,NaN,Services
3500,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,System Analyst,NaN,NaN,NaN,NaN,120.000000,175.0,100.0,NaN,USA,NaN,NaN,NaN,Services
3501,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,System Analyst,NaN,NaN,NaN,NaN,39.600000,50.0,33.0,NaN,Offshore / India,NaN,NaN,NaN,Services
4936,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,SQA Lead,NaN,NaN,NaN,NaN,120.000000,145.0,85.0,NaN,USA,NaN,NaN,NaN,Services
2647,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Technical Lead,NaN,NaN,NaN,NaN,40.500000,50.0,35.0,NaN,Offshore / India,NaN,NaN,NaN,Services
23143,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,Business Analyst,NaN,NaN,NaN,NaN,120.000000,215.0,125.0,NaN,USA,NaN,NaN,NaN,Services
18826,2021-03-25,a1t2J000005OgIuQAK,NaN,NaN,NaN,DBA/UI Team/Hosting,NaN,NaN,NaN,NaN,31.500000,45.0,30.0,NaN,Offshore / India,NaN,NaN,NaN,Services
6590,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Senior Offshore Consultant,NaN,NaN,NaN,NaN,75.000000,95.0,70.0,NaN,USA,NaN,NaN,NaN,Services
6561,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Senior Principal Consultant,NaN,NaN,NaN,NaN,300.000000,345.0,275.0,NaN,USA,NaN,NaN,NaN,Services
7254,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Senior Consultant,NaN,NaN,NaN,NaN,215.000000,275.0,200.0,NaN,USA,NaN,NaN,NaN,Services
23931,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Associate Consultant,NaN,NaN,NaN,NaN,160.000000,225.0,140.0,NaN,USA,NaN,NaN,NaN,Services
11192,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Principal Offshore Consultant,NaN,NaN,NaN,NaN,100.000000,115.0,80.0,NaN,USA,NaN,NaN,NaN,Services
11265,2021-11-02,a1t2J000005uiPmQAI,NaN,Adobe Consulting Services,NaN,Principal Consultant,NaN,NaN,NaN,NaN,255.000000,315.0,250.0,NaN,USA,NaN,NaN,NaN,Services